dashboard:
  image: rapd/united-outside
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - ROOT_URL=http://127.0.0.1
   - MONGO_URL=mongodb://mongo/meteor
   - MONGO_OPLOG=mongodb://mongo/local

mongo:
  image: mongo:latest
